 
 Feature: Test Test
 
   Scenario: Test Visut
     Given I am on "http://en.wikipedia.org/wiki/Main_Page
     Then I should see "Wiki"
     And I should now see "Muffins"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               @test_batch_find_files                                                                                                                                                                                                                                                                @example
 Feature: Example Test for WikiPedia
 
   Scenario: WikiPedia
     Given I am on "http://en.wikipedia.org/wiki/Main_Page"
     Then I should see "WikiPedia"
     Then I should see "Muffins"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
     Then I should see "Test4"
